### PR TITLE
ES6 documentation

### PR DESCRIPTION
**Pull request by PEM--**
See #52

### CODE REVIEW

**Comment by astorije** [comment]
Hey @PEM--, thank you very much for this!
Note that changes to the README should come along with the respective code comment. For example, [`.empty`'s doc in the README](https://github.com/astorije/chai-immutable#empty) matches [this comment in the code](https://github.com/astorije/chai-immutable/blob/85a579ce92818c383ac267bcc6f9e009ad4bef15/chai-immutable.js#L33-L46).

At this point, this should be tied to https://github.com/astorije/chai-immutable/issues/74, which is one of the 2 things that will trigger the v2 of this plugin.

I'll ping you when I start porting this repo to ES6.

**Comment by PEM--** [comment]
Hi @astorije. Thanks for this nice addition to my test suite. For easing the port to ES6, you should definitely have a look at: http://lebab.io/ 😉

**Comment by astorije** [comment]
Hey @PEM--, sorry for the long, loooong delay. Would you mind rebasing on `master` and fixing conflicts please? :)

**Comment by astorije** [comment]
Closing this as I expect #142 will supersede it. Thanks for your help @PEM--!!

**Pull request closed without merging**
