### PR TITLE
Implement reference comparison

### LINKED ISSUE #210: Support reference comparison
Right now, the `.to.equal` assertion after having `chai-immutable` in `chai` does "deep" comparison. It compares the keys and values of Maps, values of Lists and so on. This breaks the original behaviour of `.to.equal` in `chai`.

I understand that it is done on purpose, and test code often needs this more than reference comparison. However, when having `chai-immutable` in our specs, we can't compare references, only via `expect(a === b).to.be.true` which is not a good practice in "having readable assertions". There is even an [eslint plugin](https://github.com/turbo87/eslint-plugin-chai-expect#rules) for it.

It would be cool to:
- either change the `chai-immutable`'s `equal` to `eql` or `deep.equal` and keep `equal` for comparing references (this will break backward compatibility here, but will unify the behaviour with the rest of `chai`)
- or add a new method for comparing references, e.g. `.to.referenceEqual`

Would you be open to a PR for any of these? Or is there any other problem or issue regarding this?

### PR DESCRIPTION
**Pull request by jakubzitny**
This MR adds `referenceEqual` BDD method and `referenceEqual` and `referenceNotEqual` TDD methods according to the discussion in #210.

Close #210.

### CODE REVIEW

**Comment by jakubzitny** [comment]
I am not sure how you generate the README examples, should I just manually copy the comments from the implementation to README.md @astorije?

**Comment by jankuca** [comment]
@jakubzitny Will `expect().to.not.referenceEqual()` work?

**Comment by jakubzitny** [comment]
Yes, it's already in the test cases: https://github.com/astorije/chai-immutable/pull/218/files#diff-c1129c8b045390789fa8ff62f2c6b4a9. The `to.not`s and `not.to`s and similar chaining calls are handled by chai out of the box in the BDD API.

**Comment by astorije** [comment]
> I am not sure how you generate the README examples, should I just manually copy the comments from the implementation to README.md @astorije?

Yup, it's a very complex build step that involves copying and pasting 😅
Thanks for opening this, @jakubzitny, that's awesome, I'll be looking into your PR very shortly (and if I don't, it's because I dropped the ball and feel free to ping me!)

**Comment by astorije** [comment]
@jakubzitny, I took the liberty to add the doc in the README, and also renaming `referenceNotEqual` into `notReferenceEqual` and editing the examples a little to make them pass tests.
How do you feel about those changes? It's pretty late here so I'll let you double-check me before merging 😅

**Comment by jakubzitny** [comment]
Changes are OK. The commit messages could be better, but that's your call 😉 I can squash the `notReferenceEqual` to my implementation commit if you want. Or we can just merge it as it is, again your call 🙂

**Comment by astorije** [comment]
Heh, that's fine for this one.
Thank you very much for your help!

**Comment by astorije** [comment]
This has now be released as part of [v2.1.0](https://github.com/astorije/chai-immutable/releases/tag/v2.1.0). Thanks again!

**Pull request merged**
